
// This file was auto-generated by ML.NET Model Builder. 

using SpamDetector;

// Create single instance of sample data from first line of dataset for model input
var sampleData = new MLModel1.ModelInput()
{
    Content = @"Congratulations! You've won $1,000,000!,''Dear Lucky Winner, Congratulations! You have been selected as the winner of our international lottery. You've won $1,000,000! To claim your prize, please reply with your full name, address, phone number and bank details.''",
};

var result = MLModel1.Predict(sampleData);


Console.WriteLine(result.Content+"\n");
Console.WriteLine("It's SPAM?  "+ result.PredictedLabel);


